permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name:	李国毅
  email: 517184100@qq.com
  link: http://hacklee.github.io
  weibo: 
  github: http://github.com/hacklee

# 站点信息
title: 李国毅的博客 
description: 李国毅的博客
url: http://hacklee.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://www.qqzhi.com/uploadpic/2014-05-05/013834909.jpg
favicon: http://download.easyicon.net/ico/16348/128/

# google analytics 设置
ga:
  id: UA-54767140-1
  url: hacklee.github.io

# disqus 设置
disqus:
  shortname: httphackleegithubio