permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name:	李国毅
  email: 517184100@qq.com
  link: http://hacklee.github.io
  weibo: 
  github: http://github.com/hacklee

# 站点信息
title: 闫肃的博客 
description: 闫肃的博客
url: http://hacklee.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: hacklee.github.io

# disqus 设置
disqus:
  shortname: liguoyi-zh